export const initialProducts = [
  {
    id: "1",
    name: "Blue Shirt",
    price: "$1,000.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Women",
  },
  {
    id: "2",
    name: "Pink Sweater",
    price: "$2,000.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Men",
  },
  {
    id: "3",
    name: "Black Jacket",
    price: "$1,500.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Child",
  },
  {
    id: "4",
    name: "Green Skirt",
    price: "$1,800.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Men",
  },
  {
    id: "5",
    name: "Purple Pants",
    price: "$1,500.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Women",
  },
  {
    id: "6",
    name: "Yellow Dress",
    price: "$1,800.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Child",
  },
  {
    id: "7",
    name: "Orange Hat",
    price: "$800.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Women",
  },
  {
    id: "8",
    name: "Brown Shoes",
    price: "$1,100.00 MXN",
    image: "/shirt-test.jpeg",
    category: "Men",
  },
];
